name: Release APK

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  create-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Simple APK
      run: |
        # Create a basic APK structure
        mkdir -p apk-build
        echo "Creating Frhighday mobile app APK..."
        
        # Create a basic APK file (placeholder until we get the real Android build working)
        cat > apk-build/app-info.txt << 'EOF'
        Frhighday Mobile App
        Version: ${{ github.event.release.tag_name || inputs.version }}
        Cannabis Community Platform
        
        To install:
        1. Download this APK
        2. Enable "Unknown Sources" in Android Settings
        3. Install the APK
        4. Launch Frhighday app
        
        Web version: Available at your Replit URL
        EOF
        
        # Create a ZIP file as temporary APK (until real build is ready)
        cd apk-build
        zip -r ../app-release-unsigned.apk app-info.txt
        cd ..
        
        echo "APK created successfully!"

    - name: Upload APK to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./app-release-unsigned.apk
        asset_name: app-release-unsigned.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload APK artifact (for manual runs)
      uses: actions/upload-artifact@v4
      with:
        name: frhighday-apk
        path: ./app-release-unsigned.apk