name: Build Android APK

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create Android Project Structure
      run: |
        echo "=== Creating Complete Android Project ==="
        
        # Create directory structure
        mkdir -p android/app/src/main/java/com/frhighday/app
        mkdir -p android/app/src/main/res/values
        mkdir -p android/app/src/main/res/layout
        mkdir -p android/app/src/main/res/mipmap-anydpi-v26
        mkdir -p android/app/src/main/res/mipmap-hdpi
        mkdir -p android/app/src/main/res/mipmap-mdpi
        mkdir -p android/app/src/main/res/mipmap-xhdpi
        mkdir -p android/app/src/main/res/mipmap-xxhdpi
        mkdir -p android/app/src/main/res/mipmap-xxxhdpi
        
        # Create main build.gradle
        cat > android/build.gradle << 'EOF'
        buildscript {
            repositories {
                google()
                mavenCentral()
            }
            dependencies {
                classpath 'com.android.tools.build:gradle:8.0.0'
            }
        }
        
        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }
        EOF
        
        # Create app build.gradle
        cat > android/app/build.gradle << 'EOF'
        apply plugin: 'com.android.application'
        
        android {
            namespace "com.frhighday.app"
            compileSdkVersion 34
            defaultConfig {
                applicationId "com.frhighday.app"
                minSdkVersion 22
                targetSdkVersion 34
                versionCode 1
                versionName "1.0.0"
            }
            buildTypes {
                release {
                    minifyEnabled false
                }
            }
        }
        
        dependencies {
            implementation 'androidx.appcompat:appcompat:1.6.1'
            implementation 'androidx.core:core-ktx:1.8.0'
        }
        EOF
        
        # Create MainActivity.java
        cat > android/app/src/main/java/com/frhighday/app/MainActivity.java << 'EOF'
        package com.frhighday.app;
        
        import android.os.Bundle;
        import androidx.appcompat.app.AppCompatActivity;
        
        public class MainActivity extends AppCompatActivity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                setContentView(R.layout.activity_main);
            }
        }
        EOF
        
        # Create layout
        cat > android/app/src/main/res/layout/activity_main.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:gravity="center">
            
            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Frhighday Mobile App"
                android:textSize="24sp"
                android:textStyle="bold" />
                
            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Cannabis Community Platform"
                android:textSize="16sp"
                android:layout_marginTop="16dp" />
        
        </LinearLayout>
        EOF
        
        # Create strings.xml
        cat > android/app/src/main/res/values/strings.xml << 'EOF'
        <resources>
            <string name="app_name">Frhighday</string>
        </resources>
        EOF
        
        # Create AndroidManifest.xml (simplified)
        cat > android/app/src/main/AndroidManifest.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android">
            
            <uses-permission android:name="android.permission.INTERNET" />
            
            <application
                android:allowBackup="true"
                android:icon="@mipmap/ic_launcher"
                android:label="@string/app_name"
                android:theme="@android:style/Theme.Material.Light">
                
                <activity android:name=".MainActivity"
                    android:exported="true">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
                
            </application>
        </manifest>
        EOF
        
        # Create proper PNG icon files for all densities
        echo -n -e '\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\x0bIDATx\x9cc\xf8\x0f\x00\x00\x01\x00\x01\x00\x18\xdd\x8d\xb4\x00\x00\x00\x00IEND\xaeB`\x82' > android/app/src/main/res/mipmap-hdpi/ic_launcher.png
        echo -n -e '\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\x0bIDATx\x9cc\xf8\x0f\x00\x00\x01\x00\x01\x00\x18\xdd\x8d\xb4\x00\x00\x00\x00IEND\xaeB`\x82' > android/app/src/main/res/mipmap-mdpi/ic_launcher.png
        echo -n -e '\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\x0bIDATx\x9cc\xf8\x0f\x00\x00\x01\x00\x01\x00\x18\xdd\x8d\xb4\x00\x00\x00\x00IEND\xaeB`\x82' > android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
        echo -n -e '\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\x0bIDATx\x9cc\xf8\x0f\x00\x00\x01\x00\x01\x00\x18\xdd\x8d\xb4\x00\x00\x00\x00IEND\xaeB`\x82' > android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
        echo -n -e '\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\x0bIDATx\x9cc\xf8\x0f\x00\x00\x01\x00\x01\x00\x18\xdd\x8d\xb4\x00\x00\x00\x00IEND\xaeB`\x82' > android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
        
        # Create colors and adaptive icon
        cat > android/app/src/main/res/values/colors.xml << 'EOF'
        <resources>
            <color name="ic_launcher_background">#4CAF50</color>
            <color name="ic_launcher_foreground">#FFFFFF</color>
        </resources>
        EOF
        
        cat > android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
            <background android:drawable="@color/ic_launcher_background"/>
            <foreground android:drawable="@color/ic_launcher_foreground"/>
        </adaptive-icon>
        EOF
        
        # Create gradle files
        cat > android/settings.gradle << 'EOF'
        include ':app'
        EOF
        
        cat > android/gradle.properties << 'EOF'
        org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
        android.useAndroidX=true
        android.enableJetifier=true
        EOF
        
        echo "=== Android project created successfully ==="

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-8.0-bin.zip
        unzip -q gradle-8.0-bin.zip
        echo "$PWD/gradle-8.0/bin" >> $GITHUB_PATH

    - name: Build Android APK
      working-directory: ./android
      run: |
        echo "=== Building Android APK ==="
        gradle assembleDebug --no-daemon --stacktrace

    - name: Find and Copy APK
      working-directory: ./android
      run: |
        echo "=== Locating APK ==="
        find . -name "*.apk" -type f
        
        if [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
          cp app/build/outputs/apk/debug/app-debug.apk frhighday-mobile.apk
          echo "✅ APK successfully built and copied!"
        else
          echo "❌ APK not found"
          exit 1
        fi
        
        ls -la frhighday-mobile.apk

    - name: Upload APK to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./android/frhighday-mobile.apk
        asset_name: app-release-unsigned.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: frhighday-mobile-apk
        path: ./android/frhighday-mobile.apk
