name: Release APK

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify Android project exists
      run: |
        echo "Checking Android project structure..."
        ls -la android/
        echo "Android project verified!"

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Make Gradle wrapper executable
      run: chmod +x ./android/gradlew

    - name: Build APK
      working-directory: ./android
      run: ./gradlew assembleRelease

    - name: Sign APK (unsigned for now)
      working-directory: ./android
      run: |
        cp app/build/outputs/apk/release/app-release-unsigned.apk app-release-unsigned.apk

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./android/app-release-unsigned.apk
        asset_name: app-release-unsigned.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload APK artifact (for manual runs)
      uses: actions/upload-artifact@v4
      with:
        name: frhighday-apk
        path: ./android/app-release-unsigned.apk